### PR TITLE
Added CLI tool information

### PR DESCRIPTION
**Pull request by DobromirM**

### CODE REVIEW

**Review by ajay-gov — CHANGES_REQUESTED** [review]
The cli tool works great and the documentation is pretty concise and clear.

One suggestion: Can we add documentation on the directory structure that will be created with a brief description of the files that will be created i.e
- server.recon with the Plane class and the port
-  Main class with the name of the Plane
-  build.gradle 

Will be good to add this in the Readme in the source repo and on the website. Does this sound ok?

**Comment by DobromirM** [comment]
I've added the information to the PR and updated the Readme in the CLI tool's repo https://github.com/nstreamio/swim-create#project-structure

**Comment by ajay-gov** [comment]
Looks good, will merge after fixing issue #107

**Comment by afolson** [comment]
@ajay-gov @DobromirM Should this be closed out now? You can find the same info here: https://www.swimos.org/developer-guide/2-1-swim-create/

**Comment by ajay-gov** [comment]
Content is good, need to add it to the right place before merging, i will assign the issue to me and fix it.

**Comment by DobromirM** [comment]
Yes, I think we can close this. Regarding the documentation on the page that you've sent, the CLI tool works on windows too, or at least it did when I tested it a while back.

**Review by ajay-gov — APPROVED** [review]
Moved it to the Utilities section for now.

**Pull request merged**
