### PR TITLE
Script to enable copy code button on all code snippets

### PR DESCRIPTION
**Pull request by ajay-gov**
- The copy button here is enabled on hover
- The styling might not be great, might need work
-  The copy button doesn't look good when the top line in the code snippet is long, it is displayed on top of the code

### CODE REVIEW

**Comment by ajay-gov** [comment]
@afolson and @cwjames19 can you look at this when you get a chance, i added support for this but needs some clean up work.

**Comment by afolson** [comment]
@ajay-gov I ran into the same issue with this snippet. I was working on adding these styles to the Tailwind config but that also didn't look great. I was working on making this a bar that appears above the snippet so that we can add things like a title, buttons like this, or links to github if that works for y'all.

**Comment by ajay-gov** [comment]
> @ajay-gov I ran into the same issue with this snippet. I was working on adding these styles to the Tailwind config but that also didn't look great. I was working on making this a bar that appears above the snippet so that we can add things like a title, buttons like this, or links to github if that works for y'all.

Forgot to mention, there is commented out code in the copy-code.js that adds the copy button at the bottom instead of inside the code block. It will be easy to move that above the code block too. You can comment it out and try locaclly.

I am ok with either solution, would much rather have that feature even if it looks wonky in some cases

**Comment by afolson** [comment]
This looks good for now and fixes the one line code snippet issue. I think it's fine to merge as-is 🎉

**Comment by cwjames19** [comment]
@ajay-gov do you have an example of what this would ideally look like? I can make some changes but a reference point would be useful.

**Comment by cwjames19** [comment]
Before I merge this, lmk what you think. We can always do something more involved with a top bar another time @afolson but this still simple and decent looking i think.

https://github.com/swimos/swimos-docs/assets/14270205/84809090-5b9b-4828-a847-bb9892de226e

**Comment by afolson** [comment]
@cwjames19 Looks great!

**Review by afolson — APPROVED** [review]

**Comment by ajay-gov** [comment]
> Before I merge this, lmk what you think. We can always do something more involved with a top bar another time @afolson but this still simple and decent looking i think.
> Screen.Recording.2024-03-13.at.12.55.14.PM.mov

Looks great, thanks!

**Pull request merged**
