### PR TITLE
Blog

### LINKED ISSUE #126: Developer blog
Update the developer site to support:
- Viewing a blog post as a single page. There should be a sidebar where a user can share the post via: X/Twitter, Y-Combinator, Reddit, LinkedIn, and email.
- Viewing a list/grid of paginated blog posts.

### PR DESCRIPTION
**Pull request by SirCipher**
Closes #126.

### CODE REVIEW

**Review by ajay-gov — CHANGES_REQUESTED** [review]
Blog layout and setup looks good. Both the blog links  here are not working though
http://nstream-developer-stg.s3-website.us-west-1.amazonaws.com/swimos/swimos-docs/PR-127/3/blog/

Will merge once the blogs are accessible and reviewed

**Comment by SirCipher** [comment]
@ajay-gov i noticed that too and with some of the other header links and search bar. Is it something to do with the deployment environment? The changes work locally just fine

**Comment by ajay-gov** [comment]
Hmm weird, everything under Documentation seems to work well. Is the Blog section setup similar to how the Documentation is setup so that we can review it on the CI staging site?

**Comment by SirCipher** [comment]
Yep. It is set up in a similar way. Does it work locally for you?

**Comment by ajay-gov** [comment]
Haven''t tried it locally, i will check.

**Review by cwjames19 — COMMENTED** [review]
Overall, great work! This will make it really easy to add more blog posts in the future.

It could be because I'm testing on localhost but following the FB and LinkedIn share icons results in an error.

Are we handling the case where the blog post does not have an author?
Screenshot 2023-11-03 at 1 59 12 PM

I realize this is very nitpicky so don't feel like this is a necessary change, but the text color change on hover makes it feel like the author section should have a clickable link. Probably better to just get rid of the hover effect.
https://github.com/swimos/swimos-docs/assets/14270205/6ef1afa8-357d-4717-b83d-2a413d4ef119

**Comment by afolson** [comment]
The URLs have to be generated in a specific way. There are some examples in
other templates using the link or absolute directive. I can fix it this
weekend if you want, I’m OOO today.

**Comment by cwjames19** [comment]
> The URLs have to be generated in a specific way. There are some examples in other templates using the link or absolute directive. I can fix it this weekend if you want, I’m OOO today.

No worries. I don't think we need to handle sharing a link to a local server 😄 . I should probably have been testing from the link Ajay mentioned above anyway.

**Comment by SirCipher** [comment]
@afolson if you wouldn't mind that would be appreciated

**Comment by afolson** [comment]
Will do! It’s kind of goofy so I’ll document it in the meta docs too.

**Comment by SirCipher** [comment]
@cwjames19 i did debate that but I thought that we could just default the user to 'swim' and have it populate from that - though, I didn't add said user. 

Feel free to add your suggestion regarding the hovering. Styling isn't my forte 😄

**Comment by cwjames19** [comment]
> i did debate that but I thought that we could just default the user to 'swim' and have it populate from that - though, I didn't add said user.
>
> Feel free to add your suggestion regarding the hovering. Styling isn't my forte 😄

@SirCipher I like going the route of a default 'swim' user. 👍  I went ahead and added both.

**Comment by SirCipher** [comment]
Thanks @cwjames19 😁

**Comment by afolson** [comment]
@SirCipher URLs fixed! It was a combination of changing the permalink and filtering links to render as absolute/relative paths to work on S3.

**Comment by SirCipher** [comment]
@afolson, thanks for sorting it :)

**Comment by SirCipher** [comment]
@StreamingDataApps, once this has been merged into `demo-development`, you can add your posts to that branch before we merge into `main`

**Comment by StreamingDataApps** [comment]
Excellent!

**Review by ajay-gov — APPROVED** [review]
Super, looks good to me.

**Pull request merged**
