### PR TITLE
Added 'Time Series' How To guide

### PR DESCRIPTION
**Pull request by PiggottDev**
Added 'How to Time Series Data' guide

(Haven't added to nav yet to avoid conflict with #60 )

### CODE REVIEW

**Review by ajay-gov — COMMENTED** [review]
What you have looks good. Can you add 
- [ ]  How Temporal Windowing i.e dropping data after `x` minutes can be implemented
- [ ]  Add a working example of this in the cookbooks  repo (maybe co-ordiate with @brohitbrose ) and refer to that in this doc, "something like if you want to find a full working exampe it is here"

**Comment by PiggottDev** [comment]
- Added windowing by time
- Added code snippet links (links will only work when cookbook repo PR is merged)

**Review by ajay-gov — CHANGES_REQUESTED** [review]
The code you have setups up a timer to removed data is added to the history lane after 'x' seconds. This might work but it will end up creating a timer for every element and delete just that element. Will be good to operate on the entire map instead of just the new element

There are couple of ways to do this:
Option 1: Check for data older than 'x' seconds when a new element is added as is done [here](https://github.com/swimos/tutorial/blob/master/server/src/main/java/swim/tutorial/UnitAgent.java#L52-L67). This will only check when an element is added which is similar to the size windowing. So when new elements are not added old data will remain 
Option 2: Have a timer that runs every 'y' seconds that cleans up old data where y is much less than 'x'
Option 3: Do both the above options

Maybe Option 3? If that is too complicated then Option 1 will work. @PiggottDev any thoughts?

**Comment by PiggottDev** [comment]
Sure I used this approach because it seemed the most intuitive and easiest to understand. If we don't want to have a timer per key though I can implement option 3.

I didn't like option 1 on it's own as it might be a bit misleading to call it a time window. I will add it as a separate section as a lead up to option 3.

**Comment by PiggottDev** [comment]
Changed `By Time` section to just be option 1.
Added a `By Recency` section to essentially be option 3. Will only use one timer and will calculate when it needs to trigger next to avoid unnecessary wake ups.

**Comment by ajay-gov** [comment]
> Sure I used this approach because it seemed the most intuitive and easiest to understand. If we don't want to have a timer per key though I can implement option 3.
> 
> I didn't like option 1 on it's own as it might be a bit misleading to call it a time window. I will add it as a separate section as a lead up to option 3.

Super, i love the way you did this!

**Review by ajay-gov — APPROVED** [review]
Good stuff!

**Pull request merged**
