### PR TITLE
Restructure docs to allow for language-specific sections.

### PR DESCRIPTION
**Pull request by afolson**
Overhauls docs structure so that we can have sections for server/client docs for each language.

Todos:

- [x] ~~Document how to add new sections~~ https://github.com/swimos/swimos-docs/issues/202
- [x] Add redirects for content that was moved
- [x] Add blog back to menu
- [x] Fix issue where menus briefly display on page load (x-cloak not working on docs pages, works on regular pages)
- [x] Create index pages for server, client, and concepts sections
- [x] ~~Overhaul home page to direct folks to relevant documentation~~ https://github.com/swimos/swimos-docs/issues/203
- [x] Tidy up menu icons once sections are finalized
- [x] Docs menu should highlight current section/add hover effect
- [x] Update navbar to allow for single URLs
- [x] Add "Edit this page on GitHub" link/button back

### CODE REVIEW

**Comment by afolson** [comment]
@SirCipher @ajay-gov @cwjames19 Finally got this figured out if you want to take a look. Each section of the docs is its own collection in Jekyll since we can't have collections nested within collections, but the sections will appear grouped into one high level collection (server or client) when navigating the site.

**Comment by SirCipher** [comment]
@afolson, this looks good. One thing, when on https://deploy-preview-196--scintillating-strudel-60ff56.netlify.app/server/java/ and you click on 'Getting Started' in the sub-header it takes you to a getting started page which is language-agnostic. To me, the getting started link should be specific to Java as that is the context it is contained within (under a sub-header) but it takes you to a more general section that just contains the fundamentals and a mixture of Java and JS code blocks.  I think the getting started section is probably best under its own link in the header (next to server/client/community) for people who are completely new to SwimOS.

**Comment by ajay-gov** [comment]
> I think the getting started section is probably best under its own link in the header (next to server/client/community) for people who are completely new to SwimOS - as they might not know whether they need the client or server section to get started.

Maybe instead of "Getting Started", we can call it "SwimOS Concepts". The Getting Started Section also has the Java Libraries, we should move that under the Java section

**Comment by cwjames19** [comment]
The header at http://localhost:4000/client/typescript/ still says "Frontend". We should change it to say "Typescript".

**Review by SirCipher — APPROVED** [review]

**Comment by cwjames19** [comment]
@afolson Thanks for renaming the "Frontend" section to "Typescript". I see now that the "Introduction" group of articles got moved to the bottom of the list. Can we push them back up to the top?
Screenshot 2024-04-12 at 10 21 10 AM

**Comment by afolson** [comment]
@cwjames19 Fixed!

**Review by cwjames19 — APPROVED** [review]
@afolson Thanks for making that change. Looks good!

**Pull request merged**
